/**************************************************************************************
  Apex Class Name     : GEMS_OpportunityRequestHubController 
  Version             : 1.0
  Function            : This is controller for Request Hub in Opporunity Page.
  Test Class          : GEMS_OpptyReqHubControllerTest
  Modification Log    :
* Developer           Date                   Description
* ----------------------------------------------------------------------------                 
* Bharath             08/14/2017             Original Version
* Gokul               08/22/2017             Updated the picklist values.
* Shankar             08/25/2017             Set Line_of_Business__c field value in request
* Luke Chen           01/11/2017             Remove all code due to SFDC-7107 Merge Opportunity Request Hub code to the Account Request Hub's
**************************************************************************************/
public class GEMS_OpportunityRequestHubController {}